[package]
name = "o5m-stream"
version = "1.0.0"
description = "streaming async o5m decoder"
edition = "2018"
license = "BSD"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes","unstable"] }
futures = "0.3.13"
pin-project-lite = "0.2.6"
